### ISSUE TITLE
Xml or json - use one format passing to sense-o

### ISSUE THREAD

**Issue by juztas** [sdn-sense/sense-o-py-client#35]
As reported by Sunami and seen in the past, it all starts from here: https://github.com/sdn-sense/sense-o-py-client/blob/main/sense/client/workflow_combined_api.py#L674 (wrapping json inside xml). Need to rewrite to use in either xml or json
```
Traceback (most recent call last):
  File "src/python/RTMon/worker.py", line 271, in <module>
    worker.startwork()
  File "src/python/RTMon/worker.py", line 230, in startwork
    self._startwork()
  File "src/python/RTMon/worker.py", line 253, in _startwork
    self.main()
  File "src/python/RTMon/worker.py", line 217, in main
    self.submit_exe(filename, fout)
  File "src/python/RTMon/worker.py", line 50, in submit_exe
    manifest = self.s_getManifest(instance)
  File "/opt/devrtmon/src/python/RTMonLibs/SenseAPI.py", line 79, in s_getManifest
    response = wApi.manifest_create(dumpJson(template, self.logger))
  File "/usr/local/lib/python3.6/site-packages/sense/common.py", line 21, in wrapper
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/sense/client/workflow_combined_api.py", line 680, in manifest_create
    body_xml, **kwargs)  # noqa: E501
  File "/usr/local/lib/python3.6/site-packages/sense/common.py", line 21, in wrapper
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/sense/client/workflow_combined_api.py", line 735, in instance_si_uuid_manifest_post_with_http_info
    query_params=query_params)
  File "/usr/local/lib/python3.6/site-packages/sense/common.py", line 21, in wrapper
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/sense/client/requestwrapper.py", line 145, in request
    f"Returned code {ret.status_code} with error '{error_message}'")
ValueError: Returned code 500 with error 'Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
 at [Source: (io.undertow.servlet.spec.ServletInputStreamImpl); line: 1, column: 2]'
```

**Comment by xi-yang** [comment]
@juztas Can you elaborate? If this is a bug report, what are the steps / input to reproduce?

**Comment by xi-yang** [comment]
I see this from the sense-rtmon issue: https://github.com/esnet/sense-rtmon/issues/127#issuecomment-2441318088. But it remains unclear what was the input to the API call.

**Comment by juztas** [comment]
@xi-yang We have discussed this here: https://stackv.slack.com/archives/CFSBT7TFC/p1718389638923429

Issue is on sense-o-py-client. To repeat issue (it happens sometimes):
```
        template = {"Ports": [{
            "Port": "?terminal?",
            "Name": "?port_name?",
            "Vlan": "?vlan?",
            "Node": "?node_name?",
            "Peer": "?peer?",
            "Site": "?site?",
            "Host": [{
                "Interface": "?host_port_name?",
                "Name": "?host_name?",
                "IPv4": "?ipv4?",
                "IPv6": "?ipv6?",
                "MAC": "?mac?",
                "sparql": "SELECT DISTINCT ?host_port ?ipv4 ?ipv6 ?mac WHERE { ?vlan_port nml:isAlias ?host_vlan_port. ?host_port nml:hasBidirectionalPort ?host_vlan_port. OPTIONAL {?host_vlan_port mrs:hasNetworkAddress  ?ipv4na. ?ipv4na mrs:type \"ipv4-address\". ?ipv4na mrs:value ?ipv4.} OPTIONAL {?host_vlan_port mrs:hasNetworkAddress  ?ipv6na. ?ipv6na mrs:type \"ipv6-address\". ?ipv6na mrs:value ?ipv6.} OPTIONAL {?host_vlan_port mrs:hasNetworkAddress  ?macna. ?macna mrs:type \"mac-address\". ?macna mrs:value ?mac.} FILTER NOT EXISTS {?sw_svc mrs:providesSubnet ?vlan_subnt. ?vlan_subnt nml:hasBidirectionalPort ?host_vlan_port.} }",
                "sparql-ext": "SELECT DISTINCT ?host_name ?host_port_name  WHERE {?host a nml:Node. ?host nml:hasBidirectionalPort ?host_port. OPTIONAL {?host nml:name ?host_name.} OPTIONAL {?host_port mrs:hasNetworkAddress ?na_pn. ?na_pn mrs:type \"sense-rtmon:name\". ?na_pn mrs:value ?host_port_name.} }",
                "required": "false"
            }],
            "sparql": "SELECT DISTINCT ?vlan_port ?vlan WHERE { ?subnet a mrs:SwitchingSubnet. ?subnet nml:hasBidirectionalPort ?vlan_port. ?vlan_port nml:hasLabel ?vlan_l. ?vlan_l nml:value ?vlan. }",
            "sparql-ext": "SELECT DISTINCT ?terminal ?port_name ?node_name ?peer ?site WHERE { {?node a nml:Node. ?node nml:name ?node_name. ?node nml:hasBidirectionalPort ?terminal.  ?terminal nml:hasBidirectionalPort ?vlan_port. OPTIONAL {?terminal mrs:hasNetworkAddress ?na_pn. ?na_pn mrs:type \"sense-rtmon:name\". ?na_pn mrs:value ?port_name.} OPTIONAL {?terminal nml:isAlias ?peer.} OPTIONAL {?site nml:hasNode ?node.} OPTIONAL {?site nml:hasTopology ?sub_site. ?sub_site nml:hasNode ?node.} } UNION { ?site a nml:Topology. ?site nml:name ?node_name. ?site nml:hasBidirectionalPort ?terminal. ?terminal nml:hasBidirectionalPort ?vlan_port. OPTIONAL {?terminal mrs:hasNetworkAddress ?na_pn. ?na_pn mrs:type \"sense-rtmon:name\". ?na_pn mrs:value ?port_name.} OPTIONAL {?terminal nml:isAlias ?peer.}}}",
            "required": "true"
        }]}
        wApi = self.s_getWorkflowApi()
        wApi.si_uuid = instance['referenceUUID']
        response = wApi.manifest_create(dumpJson(template, self.logger))
```
From Chat, Alberto said:
```
it is sending request in JSON, but the data is xml: Accept: application/json\r\nConnection: keep-alive\r\nContent-type: application/json\r\
```
So client - should say it is xml and not json (or we should migrate calls to json format on the client)

**Comment by juztas** [comment]
I see few issues here:
1. py client should set correct headers (either it is xml or json)
2. What is not clear - why it sometimes works and sometimes not? we need to run this in a full debug mode and compare the failing one with succeeding.

**Comment by xi-yang** [comment]
Accepting XML content with JSON header is possibly environmental. But the code is indeed flawed.

https://github.com/sdn-sense/sense-o-py-client/blob/19ddaa251febc29f64e315570c113a605ea0d999/sense/client/apiclient.py#L38-L41

There should be an option (xml or json with default to json) in the request calls.

**Comment by xi-yang** [comment]
I patched up the API client with both `content-type` and `accept-type` options for request calls. 

The manifest POST will use XML content and accept JSON return. 

The change is in PyPi now. Try the latest sense-o-api==1.35.

**Comment by juztas** [comment]
That was still an issue. Fix is here: https://github.com/sdn-sense/sense-o-py-client/pull/37

We need to set headers before issuing post/get/put call.

**Comment by abessiari** [comment]
@juztas 

Are you using retries? We use them in fabfed for all sense-api calls. That helps a lot ....

**Comment by R-Jimenez** [comment]
I went through and dug into this further, and this is now back to an orchestrator problem. The `ValueError` shown above is actually just a valid wrapper over the 500 error being returned by the orchestrator:
https://github.com/sdn-sense/sense-o-py-client/blob/18bcd18471fbd6983b5f09c1c058848c90f157b6/sense/client/requestwrapper.py#L145-L149

However I have no been able to reproduce this with local testing, once I do I will update whether this may be a timing issue or require a bugfix issue on the orchestrator itself.

**Comment by juztas** [comment]
This seems to continue to happen. Here is how I was able to replicate this:
1. Create a task, wait for it to be created-ready, and stable. Enable RTMon monitoring.
2. Monitoring will kick in and will try to create_manifest (and get manifest). Here are the logs
```
Fri, 11 Apr 2025 14:16:58.931 - RTMonLibs.LogLib - INFO - Submit Execution: rtmon-debug-sense-o.es.net-8cb383ba-42ac-47aa-a2db-52811a9248e0, {'state': 'renew', 'referenceUUID': '8cb383ba-42ac-47aa-a2db-52811a9248e0', 'orchestrator': 'sense-o.es.net', 'submission': 'AUTH
_KEY', 'taskinfo': {'uuid': '8bc6e0f4-a973-40c9-b372-41a55d03ce0e', 'agent': 'rtmon.instance-manager', 'created': '2025-04-11T14:16:34Z', 'status': 'PENDING', 'statusTime': '2025-04-11T14:16:34Z', 'config': {'register': True, 'deployment': 'Real Time Mon', 'uuid': '8cb3
83ba-42ac-47aa-a2db-52811a9248e0'}}}
Fri, 11 Apr 2025 14:16:59.436 - RTMonLibs.LogLib - INFO - Here is instance for 8cb383ba-42ac-47aa-a2db-52811a9248e0:
Fri, 11 Apr 2025 14:16:59.437 - RTMonLibs.LogLib - INFO - {'alias': 'globus-bgp-fffc-11c',
 'archived': False,
 'intents': [{'creation_time': '2025-04-10 20:18:46',
              'id': 'ebb7fd54-f15e-4bcc-869b-3d91a4a60f22',
              'json': {'data': {'connections': [{'bandwidth': {'capacity': '10000',
                                                               'qos_class': 'guaranteedCapped'},
                                                 'ip_address_pool': {'name': 'AutoGOLE-Test-IPv6-Pool',
                                                                     'netmask': '/64'},
                                                 'name': 'Connection 1',
                                                 'terminals': [{'assign_ip': True,
                                                                'ipv6_prefix_list': '2605:d9c0:2:fffc::/64',
                                                                'uri': 'urn:ogf:network:ultralight.org:2013',
                                                                'vlan_tag': 'any'},
                                                               {'assign_ip': True,
                                                                'ipv6_prefix_list': '2001:48d0:3001:11c::/64',
                                                                'uri': 'urn:ogf:network:nrp-nautilus.io:2020',
                                                                'vlan_tag': 'any'}]}],
                                'type': 'Site-L3 over P2P VLAN'},
                       'options': [],
                       'queries': [],
                       'service': 'dnc',
                       'service_instance_uuid': '8cb383ba-42ac-47aa-a2db-52811a9248e0',
                       'service_profile_uuid': 'f9d91e18-fe05-445a-abb1-2fd71aed4ba6'},
              'provisioned': True,
              'serviceDeltaUUID': '298ca753-5f47-48eb-b860-77e8d3c84da5',
              'serviceInstanceUUID': '8cb383ba-42ac-47aa-a2db-52811a9248e0'}],
 'lastState': 'COMMITTED',
 'owner': 'mlink@uchicago.edu',
 'profileUUID': 'f9d91e18-fe05-445a-abb1-2fd71aed4ba6',
 'referenceUUID': '8cb383ba-42ac-47aa-a2db-52811a9248e0',
 'state': 'CREATE - READY',
 'timestamp': '2025/04/10 20:18:46'}
Fri, 11 Apr 2025 14:18:31.941 - RTMonLibs.LogLib - ERROR - Failed to get manifest from SENSE-O for 8cb383ba-42ac-47aa-a2db-52811a9248e0: Returned code 500 with error 'Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
 at [Source: (io.undertow.servlet.spec.ServletInputStreamImpl); line: 1, column: 2]'
Fri, 11 Apr 2025 14:23:32.622 - RTMonLibs.LogLib - ERROR - Failed to get manifest from SENSE-O for 8cb383ba-42ac-47aa-a2db-52811a9248e0: Returned code 500 with error 'Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
 at [Source: (io.undertow.servlet.spec.ServletInputStreamImpl); line: 1, column: 2]'
Fri, 11 Apr 2025 14:28:33.655 - RTMonLibs.LogLib - ERROR - Failed to get manifest from SENSE-O for 8cb383ba-42ac-47aa-a2db-52811a9248e0: Returned code 500 with error 'Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
 at [Source: (io.undertow.servlet.spec.ServletInputStreamImpl); line: 1, column: 2]'
Fri, 11 Apr 2025 14:28:39.572 - RTMonLibs.LogLib - INFO - Here is manifest for the following instance:
Fri, 11 Apr 2025 14:28:39.574 - RTMonLibs.LogLib - INFO - {'Ports': [{'IPv4': '?port_ipv4?',
            'IPv6': '?port_ipv6?',
            'Mac': '28:e7:1d:3f:53:70',
            'Name': 'Port-Channel502',
            'Node': 'NRM_CENIC:aristaeos_s0',
            'Peer': 'urn:ogf:network:sense-oasis-nrp-nautilus.io:2020:oasis:Pc502',
            'Port': 'urn:ogf:network:sc-test.cenic.net:2020:aristaeos_s0:Port-Channel502',
            'Site': 'urn:ogf:network:sc-test.cenic.net:2020',
            'Vlan': '3618'},
```
As you can see, it got a task, and then 3 times in a row, it failed to get a manifest. 
Request 0 - took from 14:16:59.437 to 14:18:31.941 (It took 1m, 30s to return failure)
Request 1 - took from  14:18:31.941 to 14:23:32.622 (It took ~5m, that is the default SENSE_TIMEOUT)
Request 2 - took from 14:23:32.622 to 14:28:33.655 (It took ~5m, that is the default SENSE_TIMEOUT)
Request 3 - took from 14:28:33.655 to 14:28:39.574 (Success).

**Comment by R-Jimenez** [comment]
I took a look at the stack trace provided on Slack, and unfortunately it was purely bound to the Wildfly interceptor and filter. This is becoming a problem searching for an overwrought solution, so for me the next step is to simply correct and simplify the API access here; we'll start by redirecting the py-client to use the JSON-only endpoint at `/manifest/{svcUUID}/json`, and see if we can fully separate the two endpoints so they serve discrete content-types.

I've always been annoyed by the XML input as it's a bit of a weird pattern (wrap raw JSON within an XML and turn back into JSON), due to how old this function is (one of our earliest endpoints, about 9 years old) This newer endpoint can isolate whether we're seeing some communications issue or if the manifest code needs some deeper bug fixing.

**Comment by R-Jimenez** [comment]
Commit https://github.com/sdn-sense/sense-o-py-client/commit/67e482c431f4a21a4c0caf50481103bc9bc98215 has changed the manifest query endpoint to one that is explicitly for json data only. Will track updates and retests after the patch version gets built and pushed.

**Comment by R-Jimenez** [comment]
This patch has been deployed to dev3 and sense-o-dev.

**Comment by juztas** [comment]
rtmon uses the new version and has seen no issues for the last week. Looks to be finally solved! Thank you!
